In [17]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [23]:
class NeuralNetwork:
    def __init__(self, input_neurons, hidden_neurons, output_neurons):
        self.weights_input_hidden = np.random.randn(input_neurons, hidden_neurons)
        self.bias_hidden = np.random.randn(1, hidden_neurons)
        self.weights_hidden_output = np.random.randn(hidden_neurons, output_neurons)
        self.bias_output = np.random.randn(1, output_neurons)

    def train(self, X, y, learning_rate=0.1, epochs=10000):
        for epoch in range(epochs):
            # Forward pass
            hidden_layer_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
            hidden_layer_output = sigmoid(hidden_layer_input)
            output_layer_input = np.dot(hidden_layer_output, self.weights_hidden_output) + self.bias_output
            output_layer_output = sigmoid(output_layer_input)
            error = y - output_layer_output
            d_output = error * sigmoid_derivative(output_layer_output)
            d_hidden = np.dot(d_output, self.weights_hidden_output.T) * sigmoid_derivative(hidden_layer_output)
            self.weights_hidden_output += learning_rate * np.dot(hidden_layer_output.T, d_output)
            self.bias_output += learning_rate * np.sum(d_output, axis=0, keepdims=True)
            self.weights_input_hidden += learning_rate * np.dot(X.T, d_hidden)
            self.bias_hidden += learning_rate * np.sum(d_hidden, axis=0, keepdims=True)

    def predict(self, X):
        hidden_layer_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, self.weights_hidden_output) + self.bias_output
        output_layer_output = sigmoid(output_layer_input)
        return output_layer_output
            

In [24]:
nn = NeuralNetwork(input_neurons=2, hidden_neurons=2, output_neurons=1)

# XOR input and output
test_input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
test_output = np.array([[0], [1], [1], [0]])

nn.train(test_input, test_output)

[[0.51590413]
 [0.50420276]
 [0.53865406]
 [0.50448383]]
[[0.51496572]
 [0.50313504]
 [0.53792023]
 [0.50350774]]
[[0.51406855]
 [0.50211381]
 [0.53722049]
 [0.50257306]]
[[0.5132108 ]
 [0.50113706]
 [0.53655337]
 [0.50167796]]
[[0.51239077]
 [0.50020283]
 [0.53591745]
 [0.50082073]]
[[0.51160682]
 [0.49930926]
 [0.53531139]
 [0.49999969]]
[[0.51085735]
 [0.49845457]
 [0.53473389]
 [0.49921327]]
[[0.51014086]
 [0.49763704]
 [0.53418372]
 [0.49845995]]
[[0.50945591]
 [0.49685504]
 [0.53365968]
 [0.49773825]]
[[0.5088011 ]
 [0.496107  ]
 [0.53316065]
 [0.4970468 ]]
[[0.50817512]
 [0.49539142]
 [0.53268552]
 [0.49638425]]
[[0.50757668]
 [0.49470687]
 [0.53223326]
 [0.49574933]]
[[0.50700458]
 [0.49405197]
 [0.53180288]
 [0.49514081]]
[[0.50645766]
 [0.49342542]
 [0.5313934 ]
 [0.49455753]]
[[0.50593479]
 [0.49282596]
 [0.53100392]
 [0.49399836]]
[[0.50543493]
 [0.49225238]
 [0.53063356]
 [0.49346225]]
[[0.50495704]
 [0.49170354]
 [0.53028149]
 [0.49294815]]
[[0.50450016]
 [0.49117834]
 [0

In [25]:
# test the model
result = nn.predict([0, 1])
print(result)

[[0.95919602]]


In [3]:
# Define network architecture
input_neurons = 2
hidden_neurons = 4  # Can be changed
output_neurons = 1

In [4]:
# Initialize weights and biases randomly
np.random.seed(42)  # For reproducibility
weights_input_hidden = np.random.randn(input_neurons, hidden_neurons)
bias_hidden = np.random.randn(1, hidden_neurons)
weights_hidden_output = np.random.randn(hidden_neurons, output_neurons)
bias_output = np.random.randn(1, output_neurons)

In [5]:
# Forward propagation
hidden_layer_input = np.dot(test_input, weights_input_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
output_layer_output = sigmoid(output_layer_input)

In [6]:
# Print results
print("XOR Inputs:")
print(test_input)
print("\nPredicted Outputs:")
print(output_layer_output)

XOR Inputs:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Predicted Outputs:
[[0.04685694]
 [0.02513092]
 [0.03240043]
 [0.01986309]]
